export const LOGGED_IN_ADMIN = 'LOGGED_IN_ADMIN';
export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const LOGOUT = 'LOGOUT';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const FETCH_SUB_CATEGORIES = 'FETCH_SUB_CATEGORIES'
export const CREATE_SUB_CATEGORY = 'CREATE_SUB_CATEGORY'
export const FETCH_SUB_CATEGORY = 'FETCH_SUB_CATEGORY'
export const UPDATE_SUB_CATEGORY = 'UPDATE_SUB_CATEGORY'
export const DELETE_SUB_CATEGORY = 'DELETE_SUB_CATEGORY'

export const FETCH_BRANDS = 'FETCH_BRANDS'
export const FETCH_BRAND = 'FETCH_BRAND'
export const CREATE_BRAND = 'CREATE_BRAND'
export const UPDATE_BRAND = 'UPDATE_BRAND'
export const DELETE_BRAND = 'DELETE_BRAND'

export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const IMAGE_UPLOAD = 'IMAGE_UPLOAD'
export const IMAGE_REMOVE = 'IMAGE_REMOVE'

export const FETCH_PRODUCT_NEW_ARRIVAL = 'FETCH_PRODUCT_NEW_ARRIVAL'
export const FETCH_PRODUCT_BEST_SELL = 'FETCH_PRODUCT_BEST_SELL'